eshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name = 'cart_summary'),
    path('add/', views.cart_add, name = 'cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),    
]

eshop/checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'
urlpatterns = [
    path('', views.paypal_form, name = 'paypal_checkout'),
    path('payment-successful/', views.payment_completed, name='payment-successful'),
    path('payment-failed/', views.payment_canceled, name='payment-failed'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eshop/store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import UserLoginForm
# from .forms import ResetPasswordForm, ResetConfirmForm


app_name = 'store'
urlpatterns = [
    path('', views.product_all, name = 'product_all'),
    path('item/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('account/register/', views.user_register, name='register'),
    path('account/dashboard/', views.dashboard, name = 'dashboard'),
    path('account/<slug:uidb64>/<slug:token>/', views.user_activate, name='activate'),
    path('account/login/', auth_views.LoginView.as_view(template_name='account/login.html',
    form_class = UserLoginForm), name = 'login'),
    path('account/logout/', auth_views.LogoutView.as_view(next_page='store:login'),
    name = 'logout'),
    path('account/profile/', views.profile, name = 'profile'),
    path('account/edit_info/', views.edit_info, name = 'edit_info'),
    path('search/',views.search,name='search'),

]

eshop/cart/views.py
from urllib import response
from django.shortcuts import get_object_or_404, render
from .cart import Cart
from django.contrib import messages
from django.http import JsonResponse
from store.models import Product
# Create your views here.
def cart_summary(request):
    cart = Cart(request)
    print(cart.__len__())
    if (cart.__len__() == 0):
        messages.error(request, "Không có sản phẩm nào trong giỏ để đặt")
    return render(request, 'cart/summary.html', {'cart': cart})

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id = product_id)
        cart.add(product=product, qty = product_qty)

        cart_qty = cart.__len__()
        response = JsonResponse({'soluong': cart_qty})
        return response

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))

        cart.delete(product = product_id)

        cart_qty = cart.__len__()
        cart_total = cart.total_cart_price()
        response = JsonResponse({'cartqty': cart_qty, 'totalcartprice': cart_total})
        # return render(request, 'cart/summary.html', response)
    return response

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))

        cart.update(product = product_id, product_qty = product_qty)

        cart_qty = cart.__len__()
        cart_total = cart.total_cart_price()
        item_total = cart.total_item_price(str(product_id))
        response = JsonResponse({'cartqty': cart_qty, 'totalcartprice': cart_total, 'itemtotal': item_total})
        # return render(request, 'cart/summary.html', response) 
        return response

eshop/store/views.py
from collections import Counter
import imp
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth import login, logout
from django.contrib import messages
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count, DateField
from datetime import datetime
from .tokens import activation_token
from .models import User, Order, OrderItem
from django.http import HttpResponse
from django.db.models import Q
from django.db.models.functions import Cast
from functools import reduce
import operator
from django.db.models.functions import TruncMonth,ExtractMonth, ExtractYear

from django.core.mail import EmailMessage
from django.core.paginator import Paginator

from .models import Category, Product
from .forms import (CreateUserForm, EditInfoForm)
# Create your views here.


def product_all(request):
    products = Product.products.all()
    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    order_items = OrderItem.objects.values('product').annotate(sum_quantity = Sum('quantity')).order_by('-sum_quantity')

    # lọc product theo cách này thì được nhưng nó không còn theo thứ tự sum_quantity nữa
    #  mà nó tự sắp xếp theo thứ tự id product
    # p = products.filter(id__in=orderitem.values('product'))[:8]

    # Nên phải lấy từng id product trong top_8_product và query lại thông tin từng product rồi append vào list l
    best_selling_products = []
    for i in order_items.values('product'):
        id = i['product']
        prod = Product.objects.filter(id = id)
        best_selling_products.append(prod)

    return render(request, 'store/home.html', {'products': products, 'page_obj': page_obj, 'best_selling_products': best_selling_products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.products.filter(category = category)

    return render(request, 'products/category.html', {'category': category, 'products': products})

def search(request):
    q=request.GET.get('q')
    sorting = request.GET.get('sorting')
    data=Product.objects.filter(Q(title__icontains = q) | Q(category__title__icontains = q)).order_by('-id')
    if sorting == 'asc':
        data = data.order_by('price')
    if sorting == 'desc':
        data = data.order_by('-price')
    if sorting == 'latest':
        data = data.order_by('created')
    if not data.count():
        messages.error(request,'Không tìm thấy sản phẩm!')
    return render(request,'products/search.html',{'data':data})

def user_register(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        # We don't want anyone can be able to register account if they don't
        # actually post any data to us so this if will provide validation check.

        form = CreateUserForm(request.POST)
        # Create a form instance with POST data
        if form.is_valid():
            user = form.save(commit= False)
            # This save() method accepts an optional commit keyword argument, which accepts either True or False. 
            # If you call save() with commit=False, then it will return an object that hasn't yet been saved to the database.
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['user_name']
            user.set_password(form.cleaned_data['password'])
            user.is_active = False
            # Set is_active = False vì cần 1 thủ tục kích hoạt via email để is_active = True
            user.save()

            #Setup email
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('account/activate_account.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # encoding a byte string into base64 string so we can use it in the url,
                'token': activation_token.make_token(user),
            })
            # user.email_user(subject = subject, message = message)
            email = EmailMessage(subject = subject, body = message, to= [user.email])
            if email.send():
                # return HttpResponse("Registration Successful !" f'Dear <b>{user}</b>, please go to you email <b>{user.email}</b> inbox and click on \
                # received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.' )
                messages.success(request, 'Đã gửi mail kích hoạt tài khoản!'f' Hãy kiểm tra mail {user.email}')
            else:
                return HttpResponse(request, f'Problem sending email to {user.email}, check if you typed it correctly.')
    else:
        form = CreateUserForm()
    return render(request, 'account/register.html', {'form': form})


def user_activate(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
    try:
        pass
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and activation_token.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, 'Kích hoạt tài khoản thành công! Giờ bạn có thể đăng nhập với tài khoản vừa tạo')
        return redirect('store:login')
    else:
        return render(request, 'account/fail_to_activate.html')
    
@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request, 'account/dashboard.html', {'orders' : orders})

@login_required
def user_orders(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    return orders

@login_required
def profile(request):
    return render(
            request,
            "account/profile.html",
            )

@login_required
def edit_info(request):
    if request.method == "POST":
        user_form = EditInfoForm(instance = request.user, data = request.POST)
        
        if user_form.is_valid():
            print(user_form)
            user_form.save()
    else:
        user_form = EditInfoForm(instance = request.user)
    return render(request, "account/edit_info.html", {'user_form': user_form})

def number_order_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    count_by_month_data = orders.values('created__month').annotate(count=Count('id'))
    l = []
    for i in count_by_month_data:
        l.append({i['created__month']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def number_order_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    count_by_day_data = orders.values('created__day').annotate(count=Count('id'))
    l = []
    for i in count_by_day_data:
        l.append({i['created__day']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def revenue_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_month_data = orders.values('created__month').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_month_data:
        l.append({i['created__month']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

def revenue_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_day_data = orders.values('created__day').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_day_data:
        l.append({i['created__day']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

eshop/store/templates/store/cart/summary.html
{% extends '../base.html'%}
{% load static %}
{% load humanize %}
{% block title %} GIỎ HÀNG {% endblock %}
{% block content %}

<style>
  .checkout p, .checkout div.total {
    color: #ff6600 !important;
}
  .checkout {
    font-family: 'Roboto', sans-serif;

  }
</style>


  <main class="container my-5" id="cartList">

    <div class="row">
      <div class="col-md-9">
        <h3 class="my-4 border-bottom pb-1">Giỏ hàng của bạn</h3>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-primary {{ message.tags }}" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        <table class="table table-bordered">
      <thead>
        <tr bgcolor="grey" border="2">
          <th>Sản phẩm</th>
          <th>Số lượng</th>
          <th>Giá tiền</th>
          <th>Thành tiền</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr class="product-item" data-index="{{product.id}}">
          <td class = "w-25">
            <img src="{{ product.image.url }}" width="50" />
            <p><a href="{{item.product.get_absolute_url}}" class = "text-decoration-none fw-bold text-dark">{{product.title}}</a></p>
          </td>
          <td class="align-middle">
            {% comment %} <select id="select{{product.id}}" style="width:50px;height:31px;">
              <option value="" selected disabled hidden>{{item.soluong}}</option>
              <option value="">1</option>
              <option value="">2</option>
              <option value="">3</option>
              <option value="">4</option>
              <option value="">5</option>
            </select> {% endcomment %}
            <div class="dieuchinh">
              <span class="minus">-</span>
              <span id="product_qty{{product.id}}" class="num">{{item.soluong}}</span>
              <span class="plus">+</span>
            </div>
          </td>
          <td class = "w-25 text-center align-middle">{{product.price|intcomma}}</td>
          <td class = "w-25 text-center align-middle" id = 'item-total{{product.id}}'>{{item.total_price|intcomma}}</td>
          <td class = "w-25 text-center align-middle">
            <a type="button" id="update-button" data-index="{{product.id}}" class="update-button text-decoration-none btn btn-primary small p-2">Cập nhật</a>
            <a type="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none btn btn-danger small m-1">Xóa</a>
          </td>
        </tr>
        {% endwith %} 
        {% endfor %}
      </tbody>
    </table>
      </div>
      <div class="col-md-3">
        <h3 class="my-4 border-bottom pb-1">Thông tin hóa đơn</h3>
        <div class="card">
          <div class="card-body">
            <div class="checkout text-end">
              <p class = 'fw-bold'>Hóa đơn của bạn</p>
              <hr />
              <div class="">Tạm tính: <div id="subtotal" class="d-inline-flex text-end fw-bold">{{cart.total_cart_price|intcomma}}</div><span class="fw-bold"> đ</span></div>
              <div id="">Phí vận chuyển <span class="small">(Dự kiến 3 ngày)</span>: <span class="fw-bold"> 0 đ</span></div>
              <hr />
              <div class="pt-2">Tổng cộng: <div id="total" class="d-inline-flex fw-bold h5 total">{{cart.total_cart_price|intcomma}}</div><span class="fw-bold"> đ</span></div>
              <div class="d-grid gap-2 mt-2">
                <a role="button" href="{% url 'checkout:paypal_checkout' %}" id="order_button" class="btn btn-success fw-bold order_button" type="button">Tiến hành đặt hàng</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script>
    // Xóa sản phẩm
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          $('.product-item[data-index="' + prodid + '"]').remove();
          document.getElementById("cart_qty").innerHTML = json.cartqty
          document.getElementById("subtotal").innerHTML = parseFloat(json.totalcartprice).toLocaleString()
          document.getElementById("total").innerHTML = parseFloat(json.totalcartprice).toLocaleString()
          if (json.cartqty == 0){
            console.log("hehehe")
            document.getElementById("order_button").setAttribute("href","");
          }
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  
    // Cập nhật sản phẩm
    $(document).on('click', '.update-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_update" %}',
        data: {
          productid: $(this).data('index'),
          {% comment %} productqty: $('#select' + prodid + ' option:selected').text(), {% endcomment %}
          productqty: document.getElementById("product_qty" + prodid).innerText,
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          document.getElementById("cart_qty").innerHTML = json.cartqty
          document.getElementById("subtotal").innerHTML = parseFloat(json.totalcartprice).toLocaleString()
          document.getElementById("item-total" + prodid).innerHTML  = parseFloat(json.itemtotal).toLocaleString()
          document.getElementById("total").innerHTML = parseFloat(json.totalcartprice).toLocaleString()
          if (json.cartqty == 0){
            document.getElementById("order_button").setAttribute("href","");
          }
        },
        error: function (xhr, errmsg, err) {}
      });
    }) 
    if (cart.len == 0){
      console.log("hehehe")
      document.getElementById("order_button").setAttribute("href","");
    }
  </script> 
  <script>
    plus = document.querySelectorAll(".plus"),
    minus = document.querySelectorAll(".minus"),
    {% comment %} num = document.querySelectorAll(".num"); {% endcomment %}
    {% comment %} let a = document.getElementById("product_qty").innerText; {% endcomment %}
    {% comment %} plus.forEach(p => {
      p.addEventListener("click", ()=>{
        a++;
        a = (a < 10) ? "0" + a : a;
        num.innerText = a;
      });
    }) {% endcomment %}
    plus.forEach(p => {
      p.addEventListener("click", function(event){
        buttonClicked = event.target;
        quantity = buttonClicked.parentElement.children[1];
        new_quantity = parseInt(quantity.innerText) + 1;
        quantity.innerText = (new_quantity < 10) ? "0" + new_quantity : new_quantity;
      });
    })
    minus.forEach(m => {
      m.addEventListener("click", function(event){
        buttonClicked = event.target;
        quantity = buttonClicked.parentElement.children[1];
        new_quantity = parseInt(quantity.innerText) - 1;
        if (new_quantity > 0) {
          quantity.innerText = (new_quantity < 10) ? "0" + new_quantity : new_quantity;
        }
        else
          quantity.innerText = 0;
      });
    })

  {% comment %} var cart_len = JSON.parse("{{cart|escapejs}}"); {% endcomment %}
    {% if cart|length == 0 %}
      document.getElementById("order_button").setAttribute("href","#");
    {% endif %}

    
   </script>
{% endblock %}