eshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name = 'cart_summary'),
    path('add/', views.cart_add, name = 'cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),    
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eshop/store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import UserLoginForm
# from .forms import ResetPasswordForm, ResetConfirmForm


app_name = 'store'
urlpatterns = [
    path('', views.product_all, name = 'product_all'),
    path('item/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('account/register/', views.user_register, name='register'),
    path('account/dashboard/', views.dashboard, name = 'dashboard'),
    path('account/<slug:uidb64>/<slug:token>/', views.user_activate, name='activate'),
    path('account/login/', auth_views.LoginView.as_view(template_name='account/login.html',
    form_class = UserLoginForm), name = 'login'),
    path('account/logout/', auth_views.LogoutView.as_view(next_page='store:login'),
    name = 'logout'),
    path('account/profile/', views.profile, name = 'profile'),
    path('account/edit_info/', views.edit_info, name = 'edit_info'),
    path('search/',views.search,name='search'),

]

eshop/store/models.py
from distutils.command import upload
from enum import unique
from tabnanny import verbose
from unicodedata import category
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from datetime import datetime
from django.urls import reverse
from pkg_resources import require
from django.utils.translation import ugettext_lazy as _


# Create your models here.

class CustomUserManager(BaseUserManager):
    def create_superuser(self, email, username, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_superuser', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff = True')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser = True')
        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):
        if not email:
            raise ValueError(_('Phải nhập email !'))
        
        email = self.normalize_email(email)
        user = self.model(email = email, username = username, **other_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique = True)
    avatar = models.ImageField(upload_to='user_images/')    
    phone_number = models.CharField(max_length = 11, blank = True)
    address_1 = models.CharField(max_length = 150, blank = True)
    address_2 = models.CharField(max_length = 150, blank = True)
    # username = models.CharField(max_length = 50, unique = True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    class Meta: 
        verbose_name_plural = 'Accounts'

    def __str__(self):
        return self.username

    

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
        
class Category(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.title

class Product(models.Model):
    category = models.ForeignKey(Category, related_name = 'product', on_delete= models.CASCADE)
    created_by = models.ForeignKey(User, related_name = 'product_creator', on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    image = models.ImageField(upload_to='product_images/')
    description = models.TextField(blank= True)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=9, decimal_places=0)
    old_price = models.DecimalField(max_digits=9, decimal_places=0)    
    objects = models.Manager()
    products = ProductManager()
    
    # class Meta:
    #     ordering = ('-created',)
    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])
    
    def __str__(self):
        return self.title

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order_user')
    full_name = models.CharField(max_length=50)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, blank = True, null = True)
    city = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=10, decimal_places = 0)
    order_key = models.CharField(max_length=200)
    billing_status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
class Stock(models.Model):
    product = models.ForeignKey(Product, related_name='stock', on_delete=models.CASCADE)
    stock_quantity = models.IntegerField(default = 1)
    from_date = models.DateTimeField(auto_now_add=True)
    to_date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.id)
    


    

eshop/store/views.py
from collections import Counter
import imp
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth import login, logout
from django.contrib import messages
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count, DateField
from datetime import datetime
from .tokens import activation_token
from .models import User, Order, OrderItem
from django.http import HttpResponse
from django.db.models import Q
from django.db.models.functions import Cast
from functools import reduce
import operator
from django.db.models.functions import TruncMonth,ExtractMonth, ExtractYear

from django.core.mail import EmailMessage
from django.core.paginator import Paginator

from .models import Category, Product
from .forms import (CreateUserForm, EditInfoForm)
# Create your views here.


def product_all(request):
    products = Product.products.all()
    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    order_items = OrderItem.objects.values('product').annotate(sum_quantity = Sum('quantity')).order_by('-sum_quantity')

    # lọc product theo cách này thì được nhưng nó không còn theo thứ tự sum_quantity nữa
    #  mà nó tự sắp xếp theo thứ tự id product
    # p = products.filter(id__in=orderitem.values('product'))[:8]

    # Nên phải lấy từng id product trong top_8_product và query lại thông tin từng product rồi append vào list l
    best_selling_products = []
    for i in order_items.values('product'):
        id = i['product']
        prod = Product.objects.filter(id = id)
        best_selling_products.append(prod)

    return render(request, 'store/home.html', {'products': products, 'page_obj': page_obj, 'best_selling_products': best_selling_products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.products.filter(category = category)

    return render(request, 'products/category.html', {'category': category, 'products': products})

def search(request):
    q=request.GET.get('q')
    sorting = request.GET.get('sorting')
    data=Product.objects.filter(Q(title__icontains = q) | Q(category__title__icontains = q)).order_by('-id')
    if sorting == 'asc':
        data = data.order_by('price')
    if sorting == 'desc':
        data = data.order_by('-price')
    if sorting == 'latest':
        data = data.order_by('created')
    if not data.count():
        messages.error(request,'Không tìm thấy sản phẩm!')
    return render(request,'products/search.html',{'data':data})

def user_register(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        # We don't want anyone can be able to register account if they don't
        # actually post any data to us so this if will provide validation check.

        form = CreateUserForm(request.POST)
        # Create a form instance with POST data
        if form.is_valid():
            user = form.save(commit= False)
            # This save() method accepts an optional commit keyword argument, which accepts either True or False. 
            # If you call save() with commit=False, then it will return an object that hasn't yet been saved to the database.
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['user_name']
            user.set_password(form.cleaned_data['password'])
            user.is_active = False
            # Set is_active = False vì cần 1 thủ tục kích hoạt via email để is_active = True
            user.save()

            #Setup email
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('account/activate_account.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # encoding a byte string into base64 string so we can use it in the url,
                'token': activation_token.make_token(user),
            })
            # user.email_user(subject = subject, message = message)
            email = EmailMessage(subject = subject, body = message, to= [user.email])
            if email.send():
                # return HttpResponse("Registration Successful !" f'Dear <b>{user}</b>, please go to you email <b>{user.email}</b> inbox and click on \
                # received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.' )
                messages.success(request, 'Đã gửi mail kích hoạt tài khoản!'f' Hãy kiểm tra mail {user.email}')
            else:
                return HttpResponse(request, f'Problem sending email to {user.email}, check if you typed it correctly.')
    else:
        form = CreateUserForm()
    return render(request, 'account/register.html', {'form': form})


def user_activate(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
    try:
        pass
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and activation_token.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, 'Kích hoạt tài khoản thành công! Giờ bạn có thể đăng nhập với tài khoản vừa tạo')
        return redirect('store:login')
    else:
        return render(request, 'account/fail_to_activate.html')
    
@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request, 'account/dashboard.html', {'orders' : orders})

@login_required
def user_orders(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    return orders

@login_required
def profile(request):
    return render(
            request,
            "account/profile.html",
            )

@login_required
def edit_info(request):
    if request.method == "POST":
        user_form = EditInfoForm(instance = request.user, data = request.POST)
        
        if user_form.is_valid():
            print(user_form)
            user_form.save()
    else:
        user_form = EditInfoForm(instance = request.user)
    return render(request, "account/edit_info.html", {'user_form': user_form})

def number_order_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    count_by_month_data = orders.values('created__month').annotate(count=Count('id'))
    l = []
    for i in count_by_month_data:
        l.append({i['created__month']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def number_order_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    count_by_day_data = orders.values('created__day').annotate(count=Count('id'))
    l = []
    for i in count_by_day_data:
        l.append({i['created__day']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def revenue_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_month_data = orders.values('created__month').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_month_data:
        l.append({i['created__month']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

def revenue_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_day_data = orders.values('created__day').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_day_data:
        l.append({i['created__day']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

eshop/store/templates/store/account/activate_account.html
{% autoescape off %}
Hi {{ user.username }}
Your account has been successfully created. Please click link below to activate your account!
http://{{ domain }}{% url 'store:activate' uidb64=uid token=token %}
{% endautoescape %}

eshop/store/templates/store/account/chart_stats.html
{% extends "admin/base_site.html" %}

{% load static %}
{% comment %} <scripts href={% static 'js/stats.js' %}></scripts> {% endcomment %}

{% block content %}
<script src= "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.0/chart.min.js"> </script>
<div class="row mb-5">
    <form class='form-inline'>
        <div class="form-group">
            <label class="mx-2">Nhập tháng</label>
            <input type="number" min="1" max="12" placeholder="" name="month" class="form-control" />
        </div>
        <div class="form-group">
            <label class="mx-2">Từ ngày</label>
            <input type="date" name="from_date" class="form-control" />
        </div>
        <div class="form-group mx-sm-3">
            <label class="mx-2">Đến ngày</label>
            <input type="date" name="to_date" class="form-control" />
        </div>
        <div>
            <input type="submit" value="Lọc dữ liệu" class="btn btn-info" />
        </div>
    </form>
</div>
<div class="row mb-5">
    <div class="col-sm-6 px-5">
        <canvas id="myChart" width="400" height="500"></canvas>
    </div>
    <div class="col-sm-6 px-5">
        <canvas id="myChart2" width="400" height="500"></canvas>       
    </div>
</div>
<div class="row">
    <div class="col-sm-6 px-5">
        <canvas id="myChart3" width="400" height="500"></canvas>
    </div>
    <div class="col-sm-6 px-5">
        <canvas id="myChart4" width="400" height="500"></canvas>
    </div>
</div>

<script>

function loadChart(ctx, type, labels, data, label, x_title, y_title, colors, borderColors){

    var myChart = new Chart(ctx, {
        type: type,
        data: {
            labels: labels,
            datasets: [{
                label: label,
                data: data,
                backgroundColor: colors
                ,
                borderColor: borderColors
                ,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: y_title
                    },
                    ticks: {
                        precision: 0,
                    }
                },
                x: {
                    title: {
                        display: true,
                        text: x_title
                    }
                }
            }
        }
    });
}; 
window.onload = function() {
    let data1 = []
    let labels1 = []
    let data2 = []
    let labels2 =[]
    let data3 = []
    let labels3 =[]
    let data4 = []
    let labels4 =[]
    let colors = []
    let borderColors = []
    let colors2 = []
    let borderColors2 = []

    {% for r in revenue_by_month %}
    labels1.push({{r.0}})
    data1.push({{r.1}})
    r = Math.random() * 255
    g = Math.random() * 255
    b = Math.random() * 255
    colors.push(`rgba(${r}, ${g}, ${b}, 0.2)`)
    borderColors.push(`rgba(${r}, ${g}, {$b}, 1)`)
    {% endfor %}

    {% for c in count_by_month %}
    labels2.push({{c.0}})
    data2.push({{c.1}})
    {% endfor %}

    
    {% for r in revenue_by_day %}
    labels3.push({{r.0}})
    data3.push({{r.1}})
    r = Math.random() * 255
    g = Math.random() * 255
    b = Math.random() * 255
    colors2.push(`rgba(${r}, ${g}, ${b}, 0.2)`)
    borderColors2.push(`rgba(${r}, ${g}, {$b}, 1)`)
    {% endfor %}

    {% for c in count_by_day %}
    labels4.push({{c.0}})
    data4.push({{c.1}})
    {% endfor %}



    const ctx = document.getElementById('myChart').getContext('2d');
    const ctx2 = document.getElementById('myChart2').getContext('2d');
    const ctx3 = document.getElementById('myChart3').getContext('2d');
    const ctx4 = document.getElementById('myChart4').getContext('2d');

    loadChart(ctx, 'bar', labels1, data1, 'Doanh thu theo tháng', 'Tháng', 'Doanh thu', colors, borderColors);
    loadChart(ctx2, 'bar', labels2, data2,'Số đơn hàng theo tháng', 'Tháng', 'Số đơn', colors, borderColors);
    loadChart(ctx3, 'line', labels3, data3,'Doanh thu theo ngày', 'Ngày', 'Doanh thu', colors2, borderColors2);
    loadChart(ctx4, 'line', labels4, data4, 'Số đơn theo ngày', 'Ngày', 'Số đơn', colors2, borderColors2);

}
</script>

{% endblock %}

eshop/store/templates/store/account/dashboard.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Cart Summary{%endblock %}
{% block content %}
<style>
*{
  font-family: 'Roboto', sans-serif;
}
</style>
<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2 mb-3">Đơn hàng của bạn</h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
      <div>Quản lí <b>đơn hàng</b> và thông tin của bạn</div>
      <div><a class ="btn btn-info" href="{% url 'store:edit_info' %}">Thay đổi thông tin</a></div>
    </div>
    <hr />
  </div>
  <div class="container" style="max-width: 1000px">
    {% for order in orders %}
    <div class="row mb-4" style="border: 2px solid #ff6600;">
      
      <div class="col-12 p-3 mb-3 d-flex justify-content-between text-light" style="background-color: #346e51 !important;">
        <div class="d-flex d-flex-inline">
          <div class="pe-3 d-inline-flex"><p class ="fw-bold mx-2">Mã đơn hàng: </p> {{order.id}} | <p class ="fw-bold mx-2"> Ngày đặt: </p> {{ order.created }}</div>
          <div class="dropdown"></div>
        </div>
        <div class="text-end">
          Tổng tiền: <span class="fw-bold">{{ order.total_paid|intcomma }}</span>
        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
        <div class="d-grid gap-2 ">
          {% comment %} <button class="btn btn-warning" type="button">Hàng hóa có vấn đề ?</button>
          <button class="btn btn-primary" type="button">Bình luận</button> {% endcomment %}
        </div>
      </div>

      <div class="col-md-7 col-lg-8 p-0">

        {% for item in order.items.all %}

        <div class="card mb-3 border-0">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid" style="width:100px" src="{{item.product.image.url}}" />
            </div>
            <div class="col-md-10">
              <div class="card-body p-1">
                <a class="text-decoration-none fw-bold text-secondary" href="{{ item.product.get_absolute_url }}">
                  <p class="card-text small">{{item.product|title}}</p>
                </a>
                <p class="card-text small my-1">x{{item.quantity}}</p>
                <p class="card-text small">{{item.price|floatformat:0|intcomma}}</p>
              </div>
            </div>
          </div>
        </div>

        
        {% endfor %}


      </div>

    </div>
    {% endfor %}

  </div>
</main>






{% endblock %}

eshop/store/templates/store/account/edit_info.html
{% extends '../base.html' %}
{% block title %}Edit Profile{% endblock %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7  mx-auto">

                <form class="account-form px-4 pt-4" action="." method="post" enctype="multipart/form-data">
                    {% if user_form.is_valid%}
                    <div class="alert alert-success" role="alert">
                        Sửa thông tin thành công
                    </div>
                    <p class="small text-center pt-0">
                        <a href="{% url "store:dashboard" %}">Back to Dashboard</a>
                    </p>
                    {%else%}
                    <h3>Thay đổi thông tin của bạn</h3>
                    <p>Hãy điền theo form sau:</p>
                    {% endif %}
                    {% if user_form.errors %}
                    <div class="alert alert-primary" role="alert">
                        {{user_form.errors}}
                    </div>
                    {% endif %}
                    {% for field in user_form.errors %}
                    {% if field.errors%}
                    <div class="alert alert-primary" role="alert">
                        {{field.errors}}
                    </div>
                    {% endif %}
                    {% endfor%}
                    {% csrf_token %}
                    <label class="small font-weight-bold">{{ user_form.email.label}}</label>
                    {{ user_form.email }}
                    <label class="small font-weight-bold">{{ user_form.first_name.label}}</label>
                    {{ user_form.first_name }}
                    <label class="small font-weight-bold">{{ user_form.last_name.label}}</label>
                    {{ user_form.last_name }}
                    <label class="small font-weight-bold">{{ user_form.phone_number.label}}</label>
                    {{ user_form.phone_number }}
                    <label class="small font-weight-bold">{{ user_form.address_1.label}}</label>
                    {{ user_form.address_1 }}
                    <label class="small font-weight-bold">{{ user_form.address_2.label}}</label>
                    {{ user_form.address_2 }}




                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                        value="Save changes">Lưu thay đổi</button>
                    <hr class="mb-3">
                </form>

                <div class="text-center"><a class="px-4"href="#">Đổi mật khẩu?</a></div>

                     {% comment %} <form class="account-form px-4" action="#" method="post">
                        {% csrf_token %}
                        <p class=" h3 pt-4 font-weight-bold">Delete Account</p>
                        <p>Are you sure you want to delete your account?</p>
                        <button type="submit" role="button"
                            class="btn btn-danger btn-block py-2 mb-4 mt-5 fw-bold w-100">Delete</button>
                    </form> {% endcomment %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

eshop/store/templates/store/account/fail_to_activate.html
***Fail to activate your account

eshop/store/templates/store/account/login.html
{% extends '../base.html' %}
{% block title %} Đăng nhập
{% endblock title %}
{% block content %}
<style>
    .container-fluid {
        max-width: 100%;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6  mx-auto">
                            <form class="account-form p-4 rounded" action="{% url 'store:login' %}" method="post">

                                {% csrf_token %}
                                <h3 class="mb-4">Đăng Nhập</h3>
                                {% if messages %}
                                    {% for message in messages %}
                                    <div class="alert alert-primary {{ message.tags }}" role="alert">
                                        {{message}}
                                    </div>
                                    {% endfor %}
                                {% endif %}
                                {% if form.errors %}
                                    {% for field in form %}
                                        {% if field.errors %}
                                        <div class="alert alert-primary" role="alert">
                                            {{ field.label }}: {{ field.errors|striptags }}
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}

                                <label class="form-label">{{ form.username.label}}</label>
                                {{ form.username}}

                                <label class="form-label">{{ form.password.label}}</label>
                                {{ form.password}}
                                
                                <p class="">
                                    <a href="{% url "store:password_reset" %}">Quên mật khẩu?</a>
                                </p>
                                <div class="d-grid gap-2">
                                    <input type="hidden" name="next" value="{{ next }}">
                                    <button class="btn btn-primary py-2 mb-4 mt-4 fw-bold" type="submit" value="Log-in">Đăng nhập
                                    </button>
                                </div>
                                <p class="text-center pb-3">
                                    <a href="{% url "store:register" %}">Bạn chưa có tài khoản?</a>
                                </p>
                            </form>
                            <p class="small text-center pt-4">
                                {% comment %} <a href="{% url "password_reset" %}">Forgotten Password?</a> {% endcomment %}
                            </p>
                            <p class="small text-center">
                                {% comment %} <a href="{% url "accounts:register" %}">Help Center?</a> {% endcomment %}
                            </p>
                     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}