eshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name = 'cart_summary'),
    path('add/', views.cart_add, name = 'cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),    
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eshop/store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import UserLoginForm
# from .forms import ResetPasswordForm, ResetConfirmForm


app_name = 'store'
urlpatterns = [
    path('', views.product_all, name = 'product_all'),
    path('item/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('account/register/', views.user_register, name='register'),
    path('account/dashboard/', views.dashboard, name = 'dashboard'),
    path('account/<slug:uidb64>/<slug:token>/', views.user_activate, name='activate'),
    path('account/login/', auth_views.LoginView.as_view(template_name='account/login.html',
    form_class = UserLoginForm), name = 'login'),
    path('account/logout/', auth_views.LogoutView.as_view(next_page='store:login'),
    name = 'logout'),
    path('account/profile/', views.profile, name = 'profile'),
    path('account/edit_info/', views.edit_info, name = 'edit_info'),
    path('search/',views.search,name='search'),

]

eshop/store/models.py
from distutils.command import upload
from enum import unique
from tabnanny import verbose
from unicodedata import category
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from datetime import datetime
from django.urls import reverse
from pkg_resources import require
from django.utils.translation import ugettext_lazy as _


# Create your models here.

class CustomUserManager(BaseUserManager):
    def create_superuser(self, email, username, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_superuser', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff = True')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser = True')
        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):
        if not email:
            raise ValueError(_('Phải nhập email !'))
        
        email = self.normalize_email(email)
        user = self.model(email = email, username = username, **other_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique = True)
    avatar = models.ImageField(upload_to='user_images/')    
    phone_number = models.CharField(max_length = 11, blank = True)
    address_1 = models.CharField(max_length = 150, blank = True)
    address_2 = models.CharField(max_length = 150, blank = True)
    # username = models.CharField(max_length = 50, unique = True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    class Meta: 
        verbose_name_plural = 'Accounts'

    def __str__(self):
        return self.username

    

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
        
class Category(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.title

class Product(models.Model):
    category = models.ForeignKey(Category, related_name = 'product', on_delete= models.CASCADE)
    created_by = models.ForeignKey(User, related_name = 'product_creator', on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    image = models.ImageField(upload_to='product_images/')
    description = models.TextField(blank= True)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=9, decimal_places=0)
    old_price = models.DecimalField(max_digits=9, decimal_places=0)    
    objects = models.Manager()
    products = ProductManager()
    
    # class Meta:
    #     ordering = ('-created',)
    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])
    
    def __str__(self):
        return self.title

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order_user')
    full_name = models.CharField(max_length=50)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, blank = True, null = True)
    city = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=10, decimal_places = 0)
    order_key = models.CharField(max_length=200)
    billing_status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
class Stock(models.Model):
    product = models.ForeignKey(Product, related_name='stock', on_delete=models.CASCADE)
    stock_quantity = models.IntegerField(default = 1)
    from_date = models.DateTimeField(auto_now_add=True)
    to_date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.id)
    


    

eshop/store/views.py
from collections import Counter
import imp
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth import login, logout
from django.contrib import messages
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count, DateField
from datetime import datetime
from .tokens import activation_token
from .models import User, Order, OrderItem
from django.http import HttpResponse
from django.db.models import Q
from django.db.models.functions import Cast
from functools import reduce
import operator
from django.db.models.functions import TruncMonth,ExtractMonth, ExtractYear

from django.core.mail import EmailMessage
from django.core.paginator import Paginator

from .models import Category, Product
from .forms import (CreateUserForm, EditInfoForm)
# Create your views here.


def product_all(request):
    products = Product.products.all()
    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    order_items = OrderItem.objects.values('product').annotate(sum_quantity = Sum('quantity')).order_by('-sum_quantity')

    # lọc product theo cách này thì được nhưng nó không còn theo thứ tự sum_quantity nữa
    #  mà nó tự sắp xếp theo thứ tự id product
    # p = products.filter(id__in=orderitem.values('product'))[:8]

    # Nên phải lấy từng id product trong top_8_product và query lại thông tin từng product rồi append vào list l
    best_selling_products = []
    for i in order_items.values('product'):
        id = i['product']
        prod = Product.objects.filter(id = id)
        best_selling_products.append(prod)

    return render(request, 'store/home.html', {'products': products, 'page_obj': page_obj, 'best_selling_products': best_selling_products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.products.filter(category = category)

    return render(request, 'products/category.html', {'category': category, 'products': products})

def search(request):
    q=request.GET.get('q')
    sorting = request.GET.get('sorting')
    data=Product.objects.filter(Q(title__icontains = q) | Q(category__title__icontains = q)).order_by('-id')
    if sorting == 'asc':
        data = data.order_by('price')
    if sorting == 'desc':
        data = data.order_by('-price')
    if sorting == 'latest':
        data = data.order_by('created')
    if not data.count():
        messages.error(request,'Không tìm thấy sản phẩm!')
    return render(request,'products/search.html',{'data':data})

def user_register(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        # We don't want anyone can be able to register account if they don't
        # actually post any data to us so this if will provide validation check.

        form = CreateUserForm(request.POST)
        # Create a form instance with POST data
        if form.is_valid():
            user = form.save(commit= False)
            # This save() method accepts an optional commit keyword argument, which accepts either True or False. 
            # If you call save() with commit=False, then it will return an object that hasn't yet been saved to the database.
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['user_name']
            user.set_password(form.cleaned_data['password'])
            user.is_active = False
            # Set is_active = False vì cần 1 thủ tục kích hoạt via email để is_active = True
            user.save()

            #Setup email
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('account/activate_account.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # encoding a byte string into base64 string so we can use it in the url,
                'token': activation_token.make_token(user),
            })
            # user.email_user(subject = subject, message = message)
            email = EmailMessage(subject = subject, body = message, to= [user.email])
            if email.send():
                # return HttpResponse("Registration Successful !" f'Dear <b>{user}</b>, please go to you email <b>{user.email}</b> inbox and click on \
                # received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.' )
                messages.success(request, 'Đã gửi mail kích hoạt tài khoản!'f' Hãy kiểm tra mail {user.email}')
            else:
                return HttpResponse(request, f'Problem sending email to {user.email}, check if you typed it correctly.')
    else:
        form = CreateUserForm()
    return render(request, 'account/register.html', {'form': form})


def user_activate(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
    try:
        pass
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and activation_token.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, 'Kích hoạt tài khoản thành công! Giờ bạn có thể đăng nhập với tài khoản vừa tạo')
        return redirect('store:login')
    else:
        return render(request, 'account/fail_to_activate.html')
    
@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request, 'account/dashboard.html', {'orders' : orders})

@login_required
def user_orders(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    return orders

@login_required
def profile(request):
    return render(
            request,
            "account/profile.html",
            )

@login_required
def edit_info(request):
    if request.method == "POST":
        user_form = EditInfoForm(instance = request.user, data = request.POST)
        
        if user_form.is_valid():
            print(user_form)
            user_form.save()
    else:
        user_form = EditInfoForm(instance = request.user)
    return render(request, "account/edit_info.html", {'user_form': user_form})

def number_order_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    count_by_month_data = orders.values('created__month').annotate(count=Count('id'))
    l = []
    for i in count_by_month_data:
        l.append({i['created__month']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def number_order_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    count_by_day_data = orders.values('created__day').annotate(count=Count('id'))
    l = []
    for i in count_by_day_data:
        l.append({i['created__day']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def revenue_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_month_data = orders.values('created__month').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_month_data:
        l.append({i['created__month']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

def revenue_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_day_data = orders.values('created__day').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_day_data:
        l.append({i['created__day']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

eshop/store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static '/css/style5.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
    <script src= 'https://code.jquery.com/jquery-3.6.1.min.js' integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    {% comment %} <meta http-equiv="Content-Security-Policy" content="default-src 'self'; child-src 'none'; object-src 'none'"> {% endcomment %}

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light border-bottom p-3" style="background-color: #346e51 !important;">
            <div class="container">
                <a class="navbar-brand text-light fw-bold" href="/">Hasake</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Loại
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.title|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        
                    </ul>
                    <form id="form-search-id"class="d-flex mx-2" action="{% url "store:search" %}">
                        <input id="search-id" name = "q" class="form-control me-1 search_class"  type="text" placeholder="Tìm kiếm" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit" id = "search_button"><img src="https://hasaki.vn/images/graphics/icon_search_48x48_white.png" class="icon_search w-50 loading" data-was-processed="true"></button>
                    </form>
                    <a name="" id="" class="btn btn-outline-light ms-2 position-relative mx-2" href="{% url "cart:cart_summary" %}" role="button">
                        <svg xmlns="https://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket2" viewBox="0 0 16 16">
                            <path d="M4 10a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 1 1 2 0v2a1 1 0 0 1-2 0v-2z"/>
                            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-.623l-1.844 6.456a.75.75 0 0 1-.722.544H3.69a.75.75 0 0 1-.722-.544L1.123 8H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.163 8l1.714 6h8.246l1.714-6H2.163z"/>
                            <span id="cart_qty" class="position-absolute top-30 start-100 translate-middle badge rounded-pill bg-danger">
                                {% with total_qty=cart|length %}
                                    {% if total_qty > 0 %}
                                        {{total_qty}}
                                    {% else %}
                                        0
                                    {% endif %}
                                {% endwith %}
                                <span class="visually-hidden">unread messages</span>
                            </span>
                        </svg> 
                        
                    </a>

                    <ul class="navbar-nav mb-2 mb-md-0">
                        <li class="nav-item dropdown account ms-2">
                            <a class="nav-link dropdown-toggle  btn btn-outline-light" style="padding: 6px 12px;" href="#" id="navbarDropdownAccount" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                            {% else %}
                                Tài khoản
                            {% endif%}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                         
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'store:profile' %}">Thông tin người dùng</a></li>
                                <li><a class="dropdown-item" href="{% url 'store:dashboard' %}">Đơn hàng của bạn</a></li>
                                {% if user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                                {% endif %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'store:logout' %}">Đăng xuất</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'store:login' %}">Đăng nhập</a></li>
                                <li><a class="dropdown-item" href="{% url 'store:register' %}">Đăng kí</a></li>   
                            {% endif %}
                    
                            </ul>
                          </li>
                    </ul>
                </div>



            </div>
        </nav>
    </header> 

    <div id="content" class="container">{% block content %} {% endblock %}</div>
    <hr>
    
    <footer class="container py-5">
        <div class="row">
          <div class="col-3 col-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
            <small class="d-block mb-3 text-muted">© 2023-2024</small>
          </div>
          <div class="col-3 col-md">
            <h5>Liên hệ</h5>
            <ul class="list-unstyled text-small">
              <li><img width="30" height="30" src="https://img.icons8.com/material-outlined/30/mail.png" alt="mail"/>1951012145tri@ou.edu.vn</li>
              <li class='mt-2'><img width="30" height="30" src="https://img.icons8.com/ios/30/phone--v1.png" alt="phone--v1"/>0853789410</li>
            </ul>
          </div>
          <div class="col-3 col-md">
            <h5>Về chúng tôi</h5>
            <ul class="list-unstyled text-small">
              <li class='mt-2'><a class="text-muted" href="#"><img width="30" height="30" src="https://img.icons8.com/ios/24/facebook-new.png" alt="facebook-new"/></a></li>
              <li class='mt-2'><a class="text-muted" href="#"><img width="30" height="30" src="https://img.icons8.com/ios/30/instagram-new--v1.png" alt="instagram-new--v1"/></a></li>
              <li class='mt-2'><a class="text-muted" href="#"><img width="30" height="30" src="https://img.icons8.com/ios/30/youtube-play--v1.png" alt="youtube-play--v1"/></a></li>
            </ul>
          </div>
          <div class="col-3 col-md">
            <h5>Địa chỉ</h5>
            <ul class="list-unstyled text-small">
                <li>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.1637553825344!2d106.677298375146!3d10.79876708935135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528d7035ef10f%3A0xf28eba62ba1c6718!2zMTFBIEhvw6BuZyBWxINuIFRo4bulLCBQaMaw4budbmcgMTUsIFBow7ogTmh14bqtbiwgVGjDoG5oIHBo4buRIEjhu5MgQ2jDrSBNaW5oIDA3MDAwMCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1696486410615!5m2!1svi!2s" width="350" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </li>
            </ul>
          </div>
          {% comment %} <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Business</a></li>
              <li><a class="text-muted" href="#">Education</a></li>
              <li><a class="text-muted" href="#">Government</a></li>
              <li><a class="text-muted" href="#">Gaming</a></li>
            </ul>
          </div> {% endcomment %}

        </div>
      </footer>
</body>
</html>