eshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name = 'cart_summary'),
    path('add/', views.cart_add, name = 'cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),    
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('paypal/', include("paypal.standard.ipn.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eshop/store/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import UserLoginForm
# from .forms import ResetPasswordForm, ResetConfirmForm


app_name = 'store'
urlpatterns = [
    path('', views.product_all, name = 'product_all'),
    path('item/<slug:slug>/', views.product_detail, name = 'product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('account/register/', views.user_register, name='register'),
    path('account/dashboard/', views.dashboard, name = 'dashboard'),
    path('account/<slug:uidb64>/<slug:token>/', views.user_activate, name='activate'),
    path('account/login/', auth_views.LoginView.as_view(template_name='account/login.html',
    form_class = UserLoginForm), name = 'login'),
    path('account/logout/', auth_views.LogoutView.as_view(next_page='store:login'),
    name = 'logout'),
    path('account/profile/', views.profile, name = 'profile'),
    path('account/edit_info/', views.edit_info, name = 'edit_info'),
    path('search/',views.search,name='search'),

]

eshop/store/models.py
from distutils.command import upload
from enum import unique
from tabnanny import verbose
from unicodedata import category
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from datetime import datetime
from django.urls import reverse
from pkg_resources import require
from django.utils.translation import ugettext_lazy as _


# Create your models here.

class CustomUserManager(BaseUserManager):
    def create_superuser(self, email, username, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_superuser', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff = True')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser = True')
        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):
        if not email:
            raise ValueError(_('Phải nhập email !'))
        
        email = self.normalize_email(email)
        user = self.model(email = email, username = username, **other_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique = True)
    avatar = models.ImageField(upload_to='user_images/')    
    phone_number = models.CharField(max_length = 11, blank = True)
    address_1 = models.CharField(max_length = 150, blank = True)
    address_2 = models.CharField(max_length = 150, blank = True)
    # username = models.CharField(max_length = 50, unique = True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    class Meta: 
        verbose_name_plural = 'Accounts'

    def __str__(self):
        return self.username

    

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
        
class Category(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.title

class Product(models.Model):
    category = models.ForeignKey(Category, related_name = 'product', on_delete= models.CASCADE)
    created_by = models.ForeignKey(User, related_name = 'product_creator', on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    image = models.ImageField(upload_to='product_images/')
    description = models.TextField(blank= True)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=9, decimal_places=0)
    old_price = models.DecimalField(max_digits=9, decimal_places=0)    
    objects = models.Manager()
    products = ProductManager()
    
    # class Meta:
    #     ordering = ('-created',)
    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])
    
    def __str__(self):
        return self.title

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order_user')
    full_name = models.CharField(max_length=50)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, blank = True, null = True)
    city = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=10, decimal_places = 0)
    order_key = models.CharField(max_length=200)
    billing_status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
class Stock(models.Model):
    product = models.ForeignKey(Product, related_name='stock', on_delete=models.CASCADE)
    stock_quantity = models.IntegerField(default = 1)
    from_date = models.DateTimeField(auto_now_add=True)
    to_date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.id)
    


    

eshop/store/views.py
from collections import Counter
import imp
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth import login, logout
from django.contrib import messages
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count, DateField
from datetime import datetime
from .tokens import activation_token
from .models import User, Order, OrderItem
from django.http import HttpResponse
from django.db.models import Q
from django.db.models.functions import Cast
from functools import reduce
import operator
from django.db.models.functions import TruncMonth,ExtractMonth, ExtractYear

from django.core.mail import EmailMessage
from django.core.paginator import Paginator

from .models import Category, Product
from .forms import (CreateUserForm, EditInfoForm)
# Create your views here.


def product_all(request):
    products = Product.products.all()
    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    order_items = OrderItem.objects.values('product').annotate(sum_quantity = Sum('quantity')).order_by('-sum_quantity')

    # lọc product theo cách này thì được nhưng nó không còn theo thứ tự sum_quantity nữa
    #  mà nó tự sắp xếp theo thứ tự id product
    # p = products.filter(id__in=orderitem.values('product'))[:8]

    # Nên phải lấy từng id product trong top_8_product và query lại thông tin từng product rồi append vào list l
    best_selling_products = []
    for i in order_items.values('product'):
        id = i['product']
        prod = Product.objects.filter(id = id)
        best_selling_products.append(prod)

    return render(request, 'store/home.html', {'products': products, 'page_obj': page_obj, 'best_selling_products': best_selling_products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.products.filter(category = category)

    return render(request, 'products/category.html', {'category': category, 'products': products})

def search(request):
    q=request.GET.get('q')
    sorting = request.GET.get('sorting')
    data=Product.objects.filter(Q(title__icontains = q) | Q(category__title__icontains = q)).order_by('-id')
    if sorting == 'asc':
        data = data.order_by('price')
    if sorting == 'desc':
        data = data.order_by('-price')
    if sorting == 'latest':
        data = data.order_by('created')
    if not data.count():
        messages.error(request,'Không tìm thấy sản phẩm!')
    return render(request,'products/search.html',{'data':data})

def user_register(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        # We don't want anyone can be able to register account if they don't
        # actually post any data to us so this if will provide validation check.

        form = CreateUserForm(request.POST)
        # Create a form instance with POST data
        if form.is_valid():
            user = form.save(commit= False)
            # This save() method accepts an optional commit keyword argument, which accepts either True or False. 
            # If you call save() with commit=False, then it will return an object that hasn't yet been saved to the database.
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            # user.username = form.cleaned_data['user_name']
            user.set_password(form.cleaned_data['password'])
            user.is_active = False
            # Set is_active = False vì cần 1 thủ tục kích hoạt via email để is_active = True
            user.save()

            #Setup email
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('account/activate_account.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # encoding a byte string into base64 string so we can use it in the url,
                'token': activation_token.make_token(user),
            })
            # user.email_user(subject = subject, message = message)
            email = EmailMessage(subject = subject, body = message, to= [user.email])
            if email.send():
                # return HttpResponse("Registration Successful !" f'Dear <b>{user}</b>, please go to you email <b>{user.email}</b> inbox and click on \
                # received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.' )
                messages.success(request, 'Đã gửi mail kích hoạt tài khoản!'f' Hãy kiểm tra mail {user.email}')
            else:
                return HttpResponse(request, f'Problem sending email to {user.email}, check if you typed it correctly.')
    else:
        form = CreateUserForm()
    return render(request, 'account/register.html', {'form': form})


def user_activate(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
    try:
        pass
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and activation_token.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, 'Kích hoạt tài khoản thành công! Giờ bạn có thể đăng nhập với tài khoản vừa tạo')
        return redirect('store:login')
    else:
        return render(request, 'account/fail_to_activate.html')
    
@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request, 'account/dashboard.html', {'orders' : orders})

@login_required
def user_orders(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    return orders

@login_required
def profile(request):
    return render(
            request,
            "account/profile.html",
            )

@login_required
def edit_info(request):
    if request.method == "POST":
        user_form = EditInfoForm(instance = request.user, data = request.POST)
        
        if user_form.is_valid():
            print(user_form)
            user_form.save()
    else:
        user_form = EditInfoForm(instance = request.user)
    return render(request, "account/edit_info.html", {'user_form': user_form})

def number_order_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    count_by_month_data = orders.values('created__month').annotate(count=Count('id'))
    l = []
    for i in count_by_month_data:
        l.append({i['created__month']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def number_order_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    count_by_day_data = orders.values('created__day').annotate(count=Count('id'))
    l = []
    for i in count_by_day_data:
        l.append({i['created__day']:i['count']})
    counter = Counter()
    for d in l:
        counter.update(d)

    result = dict(counter).items()
    return result

def revenue_by_month(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_month_data = orders.values('created__month').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_month_data:
        l.append({i['created__month']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

def revenue_by_day(orders, month = None, year = None, from_date = None, to_date = None):
    if month:
        orders = orders.filter(created__month = month)
    if from_date:
        orders = orders.filter(created__gte = from_date)
    if to_date:
        orders = orders.filter(created__lt = to_date)
    # count_by_month = orders.raw("SELECT strftime('%m', created) as month, COUNT(*) as count, id FROM store_order WHERE billing_status = True GROUP BY strftime('%m', created)")
    revenue_by_day_data = orders.values('created__day').annotate(revenue=Sum('total_paid'))
    l = []
    for i in revenue_by_day_data:
        l.append({i['created__day']:i['revenue']})
    counter = Counter()
    for d in l:
        counter.update(d)
    result = dict(counter).items()
    return result

eshop/store/templates/store/products/detail.html
{% extends "../base.html" %}
{% load humanize %}
{% block title%}
{{product.title}}
{% endblock%}
{% block content %}
<div class = "detail-section container">
    <div class = "deltail-part pt-5">
        <div class = "row g-3">
            <div class = "col-md-5 col-lg-5 order-md-first bg-light">
                <img class = "img-fluid mx-auto d-block" style="border: 2px solid #346e51;" width = "380px" src="{{product.image.url}}" alt ="Ảnh sản phẩm">
            </div>
            <div class = "col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Giá</div>
                            <div class="col-6 text-end" style="color: #ff6600;"><span class="h4 fw-bold">{{ product.price|intcomma }} đ</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                {% comment %} <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select> {% endcomment %}
                                <div class="dieuchinh">
                                    <span class="minus">-</span>
                                    <span id="product_qty" class="num">01</span>
                                    <span class="plus">+</span>
                                </div>
                                  <script>
                                   const plus = document.querySelector(".plus"),
                                    minus = document.querySelector(".minus"),
                                    num = document.querySelector(".num");
                                    let a = 1;
                                    plus.addEventListener("click", ()=>{
                                      a++;
                                      a = (a < 10) ? "0" + a : a;
                                      num.innerText = a;
                                    });
                                
                                    minus.addEventListener("click", ()=>{
                                      if(a > 1){
                                        a--;
                                        a = (a < 10) ? "0" + a : a;
                                        num.innerText = a;
                                      }
                                    });
                                
                                  </script>
                            </div>
                            <div class="col-6 text-end"><button type="button" id="add-button" value= "{{product.id}}" class="btn btn-success btn-sm">
                                {% if not product.is_active %}Hết hàng
                                {% else %}
                                Thêm vào giỏ
                                {% endif %}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<script>
    $(document).on('click', '#add-button', function (e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: document.getElementById("product_qty").innerText,
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(json){
                document.getElementById("cart_qty").innerText = json.soluong
                console.log(json)
            },
            error: function (xhr, errmsg, err){
                
            }
        });
    })
    {% if not product.is_active %}
        document.getElementById('add-button').classList.add('disabled')
    {% endif %}
</script>
{% endblock %}

eshop/store/templates/store/products/search.html
{% extends '../base.html'%}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block title %} HOME PAGE {% endblock %}
{% block content %} 
<!--SHOW PRODUCTS-->
<div class="list-product mt-5">
    <div class="row">
        <h2 class = "list-product-title">Danh sách sản phẩm</h2>
        <div class="list-product-description pb-3">
          <p>Kết quả tìm kiếm của "{{request.GET.q}}"</p>
          {% if not data %}
          {% if messages %}
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
          {% endif %}
          {% endif %}
        </div>
    </div>
    {% if data %}
    <div class="row container">
      <div class="col-9">   
      </div>
      <form class="d-inline-flex col-3">
        <label class="mt-2 mx-2">Sắp xếp theo</label>
        <div class="dropdown">
          <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Mặc định
          </button>
          <input type="hidden" name="q" value="{{request.GET.q}}">

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li>
              <input type="submit" value="asc" name="sorting" class="btn-check" id="price_asc" autocomplete="off">
              <label class="btn" for="price_asc">Giá thấp đến cao</label>
            </li>
            <li>
              <input type="submit" value="desc" name="sorting" class="btn-check" id="price_desc" autocomplete="off">
              <label class="btn" for="price_desc">Giá cao đến thấp</label>
            </li>
            <li>  
              <input type="submit" value="latest" name="sorting" class="btn-check" id="latest" autocomplete="off">
              <label class="btn" for="latest">Mới nhất</label>
            </li>
          </ul>
        </div>
      </form>
    </div>

    <hr>
    {% endif %}

      <div class="container product-group">
        <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-3">
        {% for product in data %}
        <div class="col">
          <div class="card col-product">
              <a class="text-dark text-decoration-none" href="{{product.get_absolute_url}}">
                <img class="card-img-top img-resize" src="{{ product.image.url }}" alt="Card image cap">
                
                <div class="card-body">
                  <div class="product-price">
                      <span class='new-price'>{{ product.price|intcomma}} đ</span>
                      {% if product.old_price != 0 %}
                      <span class = "discount-percent">{% widthratio product.price product.old_price 100 as sale%} {{100|sub:sale}}%</span>
                      <span class='old-price px-1'>{{product.old_price|intcomma}} đ</span>
                      {% endif %}

                  </div>
                  <p class="card-title product-title">{{ product.category.title }}</p>
                  <p class="card-text product-name mb-2">{{ product.title}}</p>
              </a>

                  <button type="button" id="add-button" data-index="{{product.id}}" class="btn btn-success w-100 add-button">Thêm vào giỏ</button>
                </div>
          </div>
        </div>
        {% endfor %}
        </div>
    </div>
</div>  

<script>
  $(document).on('click', '.add-button', function (e){
      e.preventDefault();
      $.ajax({
          type: 'POST',
          url: '{% url "cart:cart_add" %}',
          data: {
              productid: $(this).data('index'),
              productqty: 1,
              csrfmiddlewaretoken: '{{ csrf_token }}',
              action: 'post'
          },
          success: function(json){
              document.getElementById("cart_qty").innerText = json.soluong
              console.log(json)
          },
          error: function (xhr, errmsg, err){
              
          }
      });
  })
</script>
  {% endblock %} 